name: Build
on:
  push:
    branches:
      - master

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDD-HHmm'
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.time.outputs.time }}
          body_path: README.md
          token: ${{ secrets.GH_TOKEN }}
          target_commitish: master
          draft: false
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        BOARD: [hinlink-h88k]
        DISTRO: [armbian]
        FLAVOR: [debian]
        BRANCH: [legacy]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set some envs
        id: step_one
        run: |
          echo "expert=yes" >> $GITHUB_ENV
          echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
      - name: Upload Armbian image
        uses:  happyme531/armbian-compile-action@main
        if: matrix.DISTRO == 'armbian'
        with:
          branch: ${{ matrix.BRANCH }}
          board: ${{ matrix.BOARD }}
          flavor: ${{ matrix.FLAVOR }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GH_TOKEN }}
